# site settings
title: Personal Website
subtitle: by FAR
email: fathimah21001@mail.unpad.ac.id
description: Hi, I'm currently studying Digital Business and captivated to learn and explore new skills. I'm very tolerant with diversity around me and I could analyze people from so many prespective. But one thing I know for sure about my self is that, I'm very content about what I want. And how do I achieve that. In the main time, I did accomplish few experience, from oversaw a comittee and worked as an intern. I also could work in pressure but still maintain a balance life. I easily adapt with people, so working with others won't be such a big deal for me.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
street_address: C8 13 Wijayakusuma
city: Bogor
state: West Java
zip_code: 16144
country: Indonesia

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/azzahrarhdn
  Instagram: https://www.instagram.com/rahadianumb/
  LinkedIn: https://www.linkedin.com/in/fathimah-azzahra-rahadian-271002

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
